GUJARAT_CITIES = [
    "Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar",
    "Junagadh", "Gandhinagar", "Anand", "Nadiad", "Morbi", "Mehsana",
    "Surendranagar", "Gandhidham", "Veraval", "Navsari", "Bharuch",
    "Porbandar", "Bhuj", "Valsad", "Vapi", "Gondal", "Palanpur",
    "Patan", "Kalol", "Dahod", "Botad", "Amreli", "Deesa", "Jetpur",
    "Godhra", "Somnath", "Dwarka"
]

CITY_TRANSLATIONS = {
    'Ahmedabad': ['ahmedabad', 'अहमदाबाद', 'અમદાવાદ'],
    'Surat': ['surat', 'सूरत', 'સુરત'],
    'Vadodara': ['vadodara', 'वडोदरा', 'વડોદરા'],
    'Rajkot': ['rajkot', 'राजकोट', 'રાજકોડ', 'રાજકોટ'],
    'Bhavnagar': ['bhavnagar', 'भावनगर', 'ભાવનગર'],
    'Jamnagar': ['jamnagar', 'जामनगर', 'જામનગર'],
    'Junagadh': ['junagadh', 'जूनागढ़', 'જૂનાગઢ'],
    'Gandhinagar': ['gandhinagar', 'गांधीनगर', 'ગાંધીનગર'],
    'Anand': ['anand', 'आनंद', 'આણંદ'],
    'Nadiad': ['nadiad', 'नडियाद', 'નડિયાદ'],
    'Morbi': ['morbi', 'મોરબી', 'मोरबी'],
    'Mehsana': ['mehsana', 'मेहसाणा', 'મહેસાણા'],
    'Surendranagar': ['surendranagar', 'सुरेंद्रनगर', 'સુરેન્દ્રનગર'],
    'Gandhidham': ['gandhidham', 'गांधीधाम', 'ગાંધીધામ'],
    'Veraval': ['veraval', 'वेरावल', 'વેરાવળ'],
    'Navsari': ['navsari', 'नवसारी', 'નવસારી'],
    'Bharuch': ['bharuch', 'भड़ूच', 'ભરૂચ'],
    'Porbandar': ['porbandar', 'पोरबंदर', 'પોરબંદર'],
    'Bhuj': ['bhuj', 'भुज', 'ભુજ'],
    'Valsad': ['valsad', 'वलसाड', 'વલસાડ'],
    'Vapi': ['vapi', 'वापी', 'વાપી'],
    'Gondal': ['gondal', 'गोंडल', 'ગોંડલ'],
    'Palanpur': ['palanpur', 'पालनपुर', 'પાલનપુર'],
    'Patan': ['patan', 'पाटन', 'પાટણ'],
    'Kalol': ['kalol', 'कलोल', 'કલોલ'],
    'Dahod': ['dahod', 'दाहोद', 'દાહૂદ', 'દાહોદ'],
    'Botad': ['botad', 'बोताद', 'બોટાદ'],
    'Amreli': ['amreli', 'अमरेली', 'અમરેલી'],
    'Deesa': ['deesa', 'डीसा', 'ડીસા'],
    'Jetpur': ['jetpur', 'जेतपुर', 'જેતપુર'],
    'Godhra': ['godhra', 'गोधरा', 'ગોધરા'],
    'Somnath': ['somnath', 'सोमनाथ', 'સોમનાથ'],
    'Dwarka': ['dwarka', 'द्वारका', 'દ્વારકા'],
}
