# Generated by Django 5.2.14 on 2026-07-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apilimittracker_recoverytracker_recoverycheckin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycheckin',
            name='farmer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recoverycheckin',
            name='pest_activity',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='recoverycheckin',
            name='recovery_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recoverytracker',
            name='estimated_recovery_weeks',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='recoverytracker',
            name='light_requirement',
            field=models.CharField(default='Direct Sunlight', max_length=50),
        ),
        migrations.AddField(
            model_name='recoverytracker',
            name='watering_frequency',
            field=models.CharField(default='Once a day', max_length=50),
        ),
    ]
