# Generated by Django 5.2.14 on 2026-07-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_recoverycheckin_farmer_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycheckin',
            name='week_number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='recoverytracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='recoverytracker',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing Recovery'), ('recovered', 'Fully Recovered & Healthy')], db_index=True, default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
