# Generated by Django 5.2.14 on 2026-08-04 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_recoverycheckin_week_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverytracker',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
