# Generated by Django 5.2.14 on 2026-08-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_recoverytracker_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('gu', 'Gujarati'), ('mr', 'Marathi')], default='en', max_length=2),
        ),
    ]
