# Generated by Django 5.2.15 on 2026-07-05 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/%Y/%m/')),
                ('organ', models.CharField(choices=[('leaf', 'Leaf'), ('flower', 'Flower'), ('fruit', 'Fruit'), ('bark', 'Bark')], default='leaf', max_length=10)),
                ('identified_species', models.CharField(max_length=200)),
                ('identified_common_name', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence_score', models.FloatField()),
                ('plantnet_raw_response', models.JSONField()),
                ('matched_crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_identified', models.CharField(blank=True, max_length=100, null=True)),
                ('is_healthy', models.BooleanField()),
                ('fertilizer_recommendation', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
