# Generated by Django 5.2.14 on 2026-07-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('image_name', models.CharField(max_length=255)),
                ('organ', models.CharField(choices=[('leaf', 'Leaf'), ('flower', 'Flower'), ('fruit', 'Fruit'), ('bark', 'Bark')], default='leaf', max_length=10)),
                ('identified_species', models.CharField(max_length=200)),
                ('identified_common_name', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence_score', models.FloatField()),
                ('is_healthy', models.BooleanField()),
                ('disease_identified', models.CharField(blank=True, max_length=100, null=True)),
                ('fertilizer_recommendation', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FUTUREDATASET',
                'ordering': ['-created_at'],
            },
        ),
    ]
