# Generated by Django 5.2.14 on 2026-07-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_futuredataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuredataset',
            name='severity',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='futuredataset',
            name='treatment_application_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='futuredataset',
            name='treatment_chemical_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futuredataset',
            name='treatment_dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='futuredataset',
            name='treatment_organic_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futuredataset',
            name='treatment_type',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='severity',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='treatment_application_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='treatment_chemical_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='treatment_dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='treatment_organic_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanhistory',
            name='treatment_type',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
