# Generated by Django 5.2.14 on 2026-07-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_futuredataset_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuredataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
