# Generated by Django 5.2.14 on 2026-08-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_alter_futuredataset_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuredataset',
            name='organ',
            field=models.CharField(choices=[('leaf', 'Leaf'), ('flower', 'Flower')], default='leaf', max_length=10),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='organ',
            field=models.CharField(choices=[('leaf', 'Leaf'), ('flower', 'Flower')], default='leaf', max_length=10),
        ),
    ]
