# Generated by Django 5.2.14 on 2026-08-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_alter_futuredataset_organ_alter_scanhistory_organ'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FutureDataset',
        ),
    ]
